steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/tier-app-491210/app-repo/my-app:$SHORT_SHA', '.']

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/tier-app-491210/app-repo/my-app:$SHORT_SHA']

  # 3. Create a NEW Instance Template and Update the MIG
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instance-templates create-with-container app-template-$SHORT_SHA \
          --container-image=us-central1-docker.pkg.dev/tier-app-491210/app-repo/my-app:$SHORT_SHA \
          --tags=app-server \
          --machine-type=e2-small \
          --scopes=https://www.googleapis.com/auth/cloud-platform && \
        gcloud compute instance-groups managed rolling-action start-update app-mig \
          --version=template=app-template-$SHORT_SHA \
          --zone=us-central1-c

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/tier-app-491210/app-repo/my-app:$SHORT_SHA'
