steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/tier-app-491210/app-repo/my-app:$SHORT_SHA', '.']

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/tier-app-491210/app-repo/my-app:$SHORT_SHA']

  # 3. Trigger the Rolling Update on your app-mig
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'instance-groups'
      - 'managed'
      - 'rolling-action'
      - 'start-update'
      - 'app-mig'
      - '--version=template=projects/tier-app-491210/global/instanceTemplates/app-template-v2'
      - '--container-image=us-central1-docker.pkg.dev/tier-app-491210/app-repo/my-app:$SHORT_SHA'
      - '--zone=us-central1-c'

# THIS IS THE FIX:
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/tier-app-491210/app-repo/my-app:$SHORT_SHA'
